[refac] 회원탈퇴 로직에서 벌크 연산 삭제
Team-Hankki/hankki-server pull request #147
Opened 2024-08-08 17:04 UTC by kgy1008

## Related Issue 📌
close #146 

## Description ✔️
현재 회원이 탈퇴할 때, 회원 정보를 수정하는 과정에서(refresh token값 null처리 nickname 변경 등) 벌크 연산을 사용하고 있는데 이를 삭제하고 변경 감지로 데이터를 수정하도록 변경하였음

## To Reviewers

2024-08-19 12:33 UTC, Parkjyun requested changes
혹시 회원탈퇴할 때 userInfo의 nickname뿐만 아니라 user의 name도 알수없음으로 바꾸고
탈퇴 후 재회원가입할 때 항상 이름을 변경해주도록 변경해주실 수 있나요?
릴리즈하면 회원탈퇴 했는데도 이름을 갖고 있으면 뭔가 찝찝할 거 같아요..

2024-08-19 12:33 UTC, Parkjyun commented on src/main/java/org/hankki/hankkiserver/domain/user/model/UserInfo.java
> +        this.nickname = "알 수 없음";
직접적으로 필드를 변경하는 대신 updateNickname와 updateRefreshToken 사용하는 것은 어떨까요?

2024-08-19 12:46 UTC, Parkjyun commented on src/main/java/org/hankki/hankkiserver/external/openfeign/apple/AppleOAuthProvider.java
해당 파일의 의미 없는 log 지워주세요

2024-08-19 14:10 UTC, kgy1008 commented
말씀드린대로 코드 수정했습니다. 추가적으로 로그인을 할 때 중복되는 쿼리가 2방 나가는 로직이 있어서 이 부분을 수정하여 select 쿼리 1개만 실행되도록 수정하였습니다.(pr 설명 참고)

직접 쿼리를 사용하면 영속성 컨텍스트를 무시하고 DB에 직접 쿼리를 날리기 때문에 나중에 오류 발생의 원인이 될 수 있다고 생각했습니다. 더욱이 아직 `@Modifying` 애노테이션에 대해 잘 알지 못한 상태에서 이를 사용한 것도 좀 걸렸습니다. 때문에 더티 체킹 방식으로 데이터를 수정하는 것이 더 안전한 방법이라고 생각하여 수정하였습니다.

2024-08-21 16:02 UTC, kgy1008 commented on src/main/java/org/hankki/hankkiserver/domain/user/model/UserInfo.java
> +
하지만 생각해보니 updateNickname만 두는것도 괜찮을 것 같아 수정했습니다!

2024-08-21 16:02 UTC, merged