[feat] 족보 생성 삭제 API
Team-Hankki/hankki-server pull request #23
Opened 2024-07-08 08:56 UTC by PicturePark1101

## Related Issue 📌
close #16 

## Description ✔️
-  족보 생성 삭제 API
- 로그인이랑 연결 완료 (@UserId 필요한 create에 선언

## To Reviewers

2024-07-08 09:38 UTC, kgy1008 reviewed
수고하셨습니당

2024-07-08 09:38 UTC, kgy1008 commented on src/main/java/org/hankki/hankkiserver/api/favorite/controller/request/FavoritePostRequest.java
> +    @NotEmpty(message = "제목이 비었습니다.")
@NotEmpty 보다는 @NotBlank 어노테이션이 더 적절한 것 같습니다. 아래 내용을 참고해주세요.
https://wildeveloperetrain.tistory.com/68

2024-07-08 09:38 UTC, kgy1008 commented on src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteAdpater.java
> +  public Favorite findById(final long id) {
변수명을 단순히 id라 하는 것보다는 어떤 객체의 id인지 표현해주는 것이 좋을 것 같은데(ex) userId) 어떻게 생각하시나요?

2024-07-08 09:38 UTC, kgy1008 commented on src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteCommandService.java
> +    long userId = favoritePostCommand.memberId();
memberId말고 테이블 명 그대로 userId로 수정하는 것이 좋을 것 같습니다.

2024-07-08 09:38 UTC, kgy1008 commented on src/main/java/org/hankki/hankkiserver/domain/favorite/model/Favorite.java
> +    @Builder
클래스 레벨에 @Builder 작성해주면 해당 내용 없이도 builder 사용하실 수 있어요!

2024-07-08 16:01 UTC, kgy1008 commented on src/main/java/org/hankki/hankkiserver/api/favorite/controller/FavoriteController.java
> +@RequestMapping("/api/v1/favorites")
@RequestMapping에는 /api/v1만 남겨주세요!

2024-07-09 19:24 UTC, PicturePark1101 commented on src/main/java/org/hankki/hankkiserver/api/favorite/controller/request/FavoritePostRequest.java
> +    @NotEmpty(message = "제목이 비었습니다.")
반영했습니다 👍

2024-07-09 19:25 UTC, PicturePark1101 commented on src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteCommandService.java
> +    long userId = favoritePostCommand.memberId();
놓쳤습니다ㅜㅜ 반영했습니다!

2024-07-11 12:47 UTC, Parkjyun requested changes
고생하셨습니다

2024-07-11 12:47 UTC, Parkjyun commented on src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteFinder.java
> +  }
사소하지만 복수의 값을 반환한다면 findAllbyIds로 명명하는 것은 어떨까요?

2024-07-11 12:47 UTC, Parkjyun commented on src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteCommandService.java
> +    });
마찬가지로 userId한번만 쓰인다면 변수로 뽑지 않아도 될 것 같습니다.

2024-07-11 12:47 UTC, Parkjyun commented on src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteDeleter.java
> +
공백 맞춰주세요

2024-07-11 13:13 UTC, PicturePark1101 commented on src/main/java/org/hankki/hankkiserver/api/favorite/controller/FavoriteController.java
> +    favoriteCommandService.create(FavoritePostCommand.of(userId, request));
Service return 타입을 Long으로 변경하고 
    return favoriteRepository.save(Favorite.create(findUser, title, details)).getId();
으로 변경하겠습니다.

2024-07-11 13:14 UTC, PicturePark1101 commented on src/main/java/org/hankki/hankkiserver/api/favorite/controller/FavoriteController.java
> +  @PostMapping("/favorites/delete")
반영하겠습니다 👍

2024-07-11 13:17 UTC, PicturePark1101 commented on src/main/java/org/hankki/hankkiserver/api/favorite/controller/request/FavoritePostRequest.java
> +    List<String> details
요구사항대로 1이상 2이하로 바꾸겠습니다 그리고 제목 길이는 18자 이하로 변경되어서 그것도 반영하겠습니다!

2024-07-11 13:54 UTC, merged